{{- if .Values.backingServices.keycloak.enabled }}
{{- $keycloakName := include "backingServices.keycloak.name" . -}}
{{- $k := .Values.backingServices.keycloak -}}
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  annotations:
    {{- $k.route.annotations | toYaml | nindent 4 }}
  labels:
    app: keycloak
  namespace: {{ $k.namespace }}
  name: {{ $keycloakName }}
spec:
  host: {{ required ".route.host is required" $k.route.host }}
  to:
    kind: Service
    name: {{ $keycloakName }}
    weight: 100
  port:
  {{- if $k.route.tls.enabled }}
    targetPort: https
  {{- else }}
    targetPort: http
  {{- end }}
  {{- if $k.route.tls.enabled }}
  tls:
    termination: {{ $k.route.tls.termination }}
    insecureEdgeTerminationPolicy: Redirect
  {{- end }}
  wildcardPolicy: None
{{- end }}
