{{- range $k, $v := include "infrastructure.minIOTentants.enabled" . | fromYaml }}
---
  {{- $rootSecretObj := (lookup "v1" "Secret" $v.namespace $v.rootSecretName) | default dict -}}
  {{- $rootSecretData := (get $rootSecretObj "data") | default dict -}}
  {{- $username := (get $rootSecretData "username") | default ("minio" | b64enc) -}}
  {{- $password := (get $rootSecretData "password") | default (randAlphaNum 16 | b64enc) -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: minio
    v1.min.io/tenant: {{ $k }}
  namespace: {{ $v.namespace }}
  name: {{ $v.rootSecretName}} 
type: Opaque
data:
  username: {{ $username }}
  password: {{ $password }}
stringData:
  config.env: |-
    export MINIO_ROOT_USER="{{ $username | b64dec }}"
    export MINIO_ROOT_PASSWORD="{{ $password | b64dec }}"

---
  {{- $userSecretObj := (lookup "v1" "Secret" $v.namespace $v.storageUserSecretName) | default dict -}}
  {{- $userSecretData := (get $userSecretObj "data") | default dict -}}
  {{- $accessKey := (get $userSecretData "MINIO_ACCESS_KEY") | default (randAlphaNum 16 | b64enc ) -}}
  {{- $secretKey := (get $userSecretData "MINIO_SECRET_KEY") | default (randAlphaNum 16 | b64enc ) -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: minio
    v1.min.io/tenant: {{ $k }}
  namespace: {{ $v.namespace }}
  name: {{ $v.storageUserSecretName}} 
type: Opaque
data:
  accesskey: {{ $accessKey }}
  secretkey: {{ $secretKey }}
{{- end }}
