---
{{- include "common.serviceAccount" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: 
      - "apps"
    resources: 
      - deployments
    verbs: 
      - get
      - list
  - apiGroups: 
      - ""
    resources: 
      - secrets
    verbs: 
      - get
      - list
      - create
      - delete
      - update
      - patch
---
{{- include "common.clusterRoleBinding" . }}
