{{- $appId := "" }}
{{- $privateKey := "" }}
{{- $webhookSecret := "" }}
{{- $integrations := (default dict .Values.integrations) -}}
{{- $secretData := (default dict $integrations.github) -}}
{{- if $secretData }}
  {{- $appId = ($secretData.id | toString | b64enc) }}
  {{- $privateKey = ($secretData.publicKey | b64enc) }}
  {{- $webhookSecret = ($secretData.webhookSecret | b64enc) }}
{{- else }}
  {{- $ghSecretObj := (lookup "v1" "Secret" .Release.Namespace "rhtap-github-integration") | default dict -}}
  {{- $secretData = (get $ghSecretObj "data") | default dict -}}
  {{- if $secretData }}
    {{- $appId = (get $secretData "ID") }}
    {{- $privateKey = (get $secretData "PEM") }}
    {{- $webhookSecret = (get $secretData "WebhookSecret") }}
  {{- end }}
{{- end }}
---
{{- if $secretData }}
apiVersion: v1
kind: Secret
metadata:
  namespace: openshift-pipelines
  name: pipelines-as-code-secret
type: Opaque
data:
  github-application-id: {{ $appId }}
  github-private-key: {{ $privateKey }}
  webhook.secret: {{ $webhookSecret }}
{{- end }}