{{- $integrations := (default dict .Values.integrations) -}}
{{- $data := (default dict $integrations.gitlab) -}}
{{- if $data }}
kind: Secret
type: Opaque
apiVersion: v1
metadata:
  name: rhtap-gitlab-integration
stringData:
  host: {{ get $data "host" | default "gitlab.com" }}
  token: {{ $data.token }}
  {{- if and ( $data.clientId $data.clientSecret) }}
  clientId: {{ $data.clientId }}
  clientSecret: {{ $data.clientSecret }}
  {{- end }}
{{- end }}