{{- $integrations := (default dict .Values.integrations) -}}
{{- $data := (default dict $integrations.github) -}}
{{- if $data }}
kind: Secret
type: Opaque
apiVersion: v1
metadata:
  name: rhtap-github-integration
stringData:
  ID: {{ $data.id | quote }}
  ClientID: {{ $data.clientId }}
  ClientSecret: {{ $data.clientSecret }}
  PEM: |
{{ $data.publicKey | indent 4 }}
  Token: {{ $data.token }}
  WebhookSecret: {{ $data.webhookSecret }}
{{- end }}