{{- $integrations := (default dict .Values.integrations) -}}
{{- $data := (default dict $integrations.gitlab) -}}
{{- if $data }}
kind: Secret
type: Opaque
apiVersion: v1
metadata:
  name: rhtap-gitlab-integration
stringData:
  token: {{ $data.token }}
{{- end }}