{{ $namespace := .Release.Namespace }}
{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "rhtap-gitlab-integration") -}}
{{- $secretData := (get $secretObj "data") | default dict -}}
{{- if $secretData -}}
{{- range tuple "development" "prod" "stage" }}
---
kind: Secret
type: kubernetes.io/basic-auth
apiVersion: v1
metadata:
  name: gitlab-auth-secret
  namespace: {{ $namespace }}-app-{{ . }}
data:
  password: {{ $secretData.token }}
  username: {{ "oauth2" | b64enc }}
{{- end }}
{{- end }}