{{ $namespace := .Release.Namespace }}
{{- range tuple "development" "prod" "stage" }}
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    argocd.argoproj.io/managed-by: {{ $namespace }}
  name: {{ $namespace }}-app-{{ . }}
{{- end }}