{{ $namespace := .Release.Namespace }}
# The gitlab scenario needs the webhook secret in the Repository CR
# to be able to establish the webhook
{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "rhtap-github-integration") | default dict -}}
{{- $secretData := (get $secretObj "data") | default dict -}}
{{- if $secretData }}
{{- range tuple "development" "prod" "stage" }}
---
kind: Secret
type: Opaque
apiVersion: v1
metadata:
  name: pipelines-secret
  namespace: {{ $namespace }}-app-{{ . }}
data:
  webhook.secret: {{ $secretData.WebhookSecret }}
{{- end }}
{{- end }}