{{ $namespace := .Release.Namespace }}
{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "rhtap-trustification-integration") -}}
{{- $secretData := (get $secretObj "data") | default dict -}}
{{- if $secretData -}}
{{- range tuple "development" "prod" "stage" }}
---
kind: Secret
type: Opaque
apiVersion: v1
metadata:
  name: tpa-secret
  namespace: {{ $namespace }}-app-{{ . }}
data:
  bombastic_api_url: {{ $secretData.bombastic_api_url }}
  oidc_client_id:  {{ $secretData.oidc_client_id }}
  oidc_client_secret:  {{ $secretData.oidc_client_secret }}
  oidc_issuer_url: {{ $secretData.oidc_issuer_url }}
  {{- if $secretData.supported_cyclonedx_version }}
  supported_cyclonedx_version:  {{ $secretData.supported_cyclonedx_version }}
  {{- end }}
{{- end }}
{{- end }}