apiVersion: batch/v1
kind: Job
metadata:
  name: delete-tekton-config-if-exists
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 8
  template:
    spec:
      serviceAccountName: delete-tekton-config-sa
      restartPolicy: OnFailure
      containers:
        - name: delete-tekton-config
          image: quay.io/openshift/origin-cli:latest
          resources:
            limits:
              memory: 128Mi
          command:
            - /bin/bash
            - -c
            - |
              if [[ "{{ .Values.subscriptions.openshiftPipelines.managed }}" == "true" ]]; then
                  if oc get tektonconfig --selector="app.kubernetes.io/managed-by" -o name | grep -q "/config"; then
                    echo "TektonConfig already managed by Helm"
                    echo "Success"
                    exit 0
                  fi
                  echo "Deleting TektonConfig resource if it exists to allow helm to own the resource"

                  wait=5
                  RETRIES=24
                  for i in $(seq 1 "${RETRIES}"); do
                    date
                    echo "### [${i}/${RETRIES}] "
                    if oc get tektonconfigs.operator.tekton.dev config -o name 2>/dev/null
                      oc delete tektonconfig config
                      echo "TektonConfig already managed by Helm"
                      echo "Success"
                      exit 0
                    fi
                    echo "# Waiting for ${wait} seconds before retrying..."
                    sleep ${wait}
                  done
              else
                  echo "Skipping TektonConfig resource delete as pipeline subscription is not managed"
              fi
