{{- if .Values.subscriptions.crunchyData.enabled -}}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pgo-pdb-reader
rules:
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["get", "list", "watch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pgo-pdb-reader-binding
subjects:
  - kind: ServiceAccount
    name: pgo
    namespace: openshift-operators
roleRef:
  kind: ClusterRole
  name: pgo-pdb-reader
  apiGroup: rbac.authorization.k8s.io
{{- end }}
