---
apiVersion: rhdh.redhat.com/v1alpha1
kind: Backstage
metadata:
  name: {{ .Values.developerHub.instanceName | quote }}
  namespace: {{ .Release.Namespace }}
spec:
  application:
    appConfig:
      mountPath: /opt/app-root/src
      configMaps:
        - name: developer-hub-rhtap-app-config
    dynamicPluginsConfigMapName: developer-hub-rhtap-dynamic-plugins
    extraEnvs:
      secrets:
        - name: developer-hub-rhtap-env
    replicas: 1
    route:
      enabled: true
  database:
    enableLocalDb: true
