{{- $saName := "rhdh-kubernetes-plugin" }}
{{- $secretName := "rhtap-k8s-integration" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ $saName }}
type: kubernetes.io/service-account-token

---
{{- $sa := lookup "v1" "serviceAccount" .Release.Name $saName -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $saName }}
  namespace: {{ .Release.Namespace }}
{{- $secrets := (get $sa "secrets" | default list) }}
secrets:
  {{- /* Patch ServiceAccount secrets */}}
  {{- $secretExists := false }}
  {{- range $secrets }}
  - name: {{ .name }}
    {{- if eq .name $secretName }}
      {{- $secretExists = true }}
    {{- end }}
  {{- end }}
  {{- if not $secretExists }}
  - name: {{ $secretName }}
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $saName }}
rules:
  - apiGroups:
      - '*'
    resources:
      - pods
      - pods/log
      - configmaps
      - services
      - deployments
      - replicasets
      - horizontalpodautoscalers
      - ingresses
      - statefulsets
      - limitranges
      - resourcequotas
      - daemonsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - metrics.k8s.io
    resources:
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - argoproj.io
    resources:
      - rollouts
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
      - taskruns
    verbs:
      - get
      - list
      - watch

# The current RBAC permissions required are read-only cluster widie
# Reference:
# https://backstage.io/docs/features/kubernetes/configuration#role-based-access-control
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $saName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name:  {{ $saName }}
subjects:
  - kind: ServiceAccount
    name: {{ $saName }}
    namespace: {{ .Release.Namespace }}
