{{ $namespace := .Release.Namespace }}
{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "rhtap-gitlab-integration") -}}
{{- $secretData := (get $secretObj "data") | default dict -}}
{{- if $secretData -}}
apiVersion: v1
data:
  password: {{ $secretData.token }}
  type: {{ "git" | b64enc }}
  url: {{ print "https://" ($secretData.host | b64dec) | b64enc }}
  username: {{ "oauth2" | b64enc }}
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repo-creds
  name: gitlab-auth-secret
  namespace: {{ $namespace }}
type: Opaque
{{- end }}