{{- if .Values.infrastructure.openShiftPipelines.enabled }}
  {{- $osp := .Values.infrastructure.openShiftPipelines -}}
  {{- $name := printf "patch-%s" $osp.name }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  namespace: {{ $osp.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ $osp.namespace }}
  name: {{ $name }}
rules:
  - apiGroups: 
      - ""
    resources: 
      - secrets
    verbs: 
      - get
      - list
      - create
      - delete
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ $osp.namespace }}
  name: {{ $name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $name }}
subjects:
  - kind: ServiceAccount
    namespace: {{ $osp.namespace }}
    name: {{ $name }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $name }}
rules:
  - apiGroups: 
      - operator.tekton.dev
    resources: 
      - tektonconfigs
    verbs: 
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $name }}
subjects:
  - kind: ServiceAccount
    namespace: {{ $osp.namespace }}
    name: {{ $name }}
{{- end }}
