---
apiVersion: v2
name: tssc-integrations
description: TSSC Integrations
type: application
version: "1.6.0"
annotations:
  tssc.redhat-appstudio.github.com/depends-on: tssc-infrastructure, tssc-gitops, tssc-acs, tssc-acs-test
