{{ $namespace := .Release.Namespace }}
{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "rhtap-bitbucket-integration") -}}
{{- $secretData := (get $secretObj "data") | default dict -}}
{{- if $secretData -}}
---
kind: Secret
type: kubernetes.io/basic-auth
apiVersion: v1
metadata:
  name: bitbucket-auth-secret
  namespace: {{ $namespace }}-app-ci
data:
  password: {{ $secretData.appPassword }}
  username: {{ $secretData.username }}
{{- end }}