---
debug:
  ci: false

developerHub:
  instanceName: developer-hub
  catalogURL: __OVERWRITE_ME__
  ingressDomain: __OVERWRITE_ME__
  integrationSecrets:
    namespace: __OVERWRITE_ME__
  RBAC:
    adminUsers: __OVERWRITE_ME__
    enabled: __OVERWRITE_ME__
    orgs: __OVERWRITE_ME__
