---
acs:
  # ACS Central instance name.
  name: stackrox-central-services
  # ACS instances ingress domain.
  ingressDomain: __OVERWRITE_ME__
  # StackRox API token secret namespace and name.
  integrationSecret:
    namespace: __OVERWRITE_ME__
    name:  rhtap-acs-integration
  # ACS Central instance configuration.
  central:
    # Central instance resources configuration.
    resources: &acsCentralResources
      limits:
        cpu: 1024m
        memory: 4Gi
      requests:
        cpu: 125m
        memory: 512Mi
    # Central instance database configuration.
    db:
      # Resources requirements for the Central instance database.
      resources: *acsCentralResources
  # Controls the scanning settings for ACS scanners, both stable and v4. Which
  # includes the resource limits and scaling settings.
  scanners:
    # Vulnerability analyzer, responsible for scanning the images for potential
    # vulnerabilities using vulnerability databases ("db").
    analyzer:
      scaling: &acsScannerScaling
        autoScaling: Enabled
        maxReplicas: 3
        minReplicas: 1
        replicas: 1
      resources: &acsScannerResources
        limits:
          cpu: 250m
          memory: 1Gi
        requests:
          cpu: 125m
          memory: 256Mi
    # Indexes the vulnerability data discovered by the scanners.
    indexer:
      scaling: *acsScannerScaling
      resources: *acsScannerResources
    # Matches the vulnerability scanned data with container images running in
    # the cluster, based on configured security policies and generating alerts
    # for security teams.
    matcher:
      scaling: *acsScannerScaling
      resources: *acsScannerResources
