{{- if .Values.backingServices.acs.enabled }}
  {{- $acs := .Values.backingServices.acs }}
  {{- $name := printf "%s-acs" .Release.Name -}}
  {{- $namespace := $acs.namespace -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ $namespace }}
  name: {{ $name }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: {{ $namespace }}
  name: {{ $name }}
rules:
  - apiGroups: 
      - ""
    resources: 
      - secrets
    verbs: 
      - get
      - list
      - create
      - delete
      - update
      - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $name }}
subjects:
  - kind: ServiceAccount
    namespace: {{ $namespace }}
    name: {{ $name }}
{{- end }}
