{{- if .Values.infrastructure.odf.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: patch-noobaa-default-bucketclass
  namespace: {{ .Values.infrastructure.odf.namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: patch-bucketclass-sa
      restartPolicy: OnFailure
      containers:
        - name: patch-bucketclass
          image: registry.redhat.io/openshift4/ose-cli:latest
          command:
            - /bin/bash
            - -c
            - |
              set -e
              echo "Waiting for noobaa-default-bucket-class to be ready..."
              for i in {1..30}; do
                if oc get bucketclass noobaa-default-bucket-class -n {{ .Values.infrastructure.odf.namespace }} > /dev/null 2>&1; then
                  echo "BucketClass found!"
                  break
                fi
                echo "Waiting for BucketClass... ($i/30)"
                sleep 10
              done

              echo "Patching noobaa-default-bucket-class to use backing store '{{ .Values.infrastructure.odf.backingStoreName }}'..."
              
              oc patch bucketclass noobaa-default-bucket-class -n {{ .Values.infrastructure.odf.namespace }} --type=json -p="[
                {\"op\": \"replace\", \"path\": \"/spec/placementPolicy/tiers/0/backingStores\", \"value\": [\"{{ .Values.infrastructure.odf.backingStoreName }}\"]}
              ]"

              echo "Patch complete."
{{- end }}
