# The gitlab scenario needs the webhook secret in the Repository CR
# to be able to establish the webhook
{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "tssc-github-integration") | default dict -}}
{{- $secretData := (get $secretObj "data") | default dict -}}
{{- if $secretData }}
  {{- range .Values.appNamespaces.namespace_prefixes }}
    {{- $namespace := . }}
---
kind: Secret
type: Opaque
apiVersion: v1
metadata:
  name: pipelines-secret
  namespace: {{ $namespace }}-ci
data:
  webhook.secret: {{ $secretData.WebhookSecret }}
  {{- end }}
{{- end }}