{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "rhtap-acs-integration") -}}
{{- $secretData := (get $secretObj "data") | default dict -}}
{{- if $secretData -}}
  {{- range .Values.appNamespaces.namespace_prefixes }}
    {{- $namespace := . }}
---
kind: Secret
type: Opaque
apiVersion: v1
metadata:
  name: rox-api-token
  namespace: {{ $namespace }}-ci
data:
  rox-api-endpoint: {{ $secretData.endpoint }}
  rox-api-token: {{ $secretData.token }}
  {{- end }}
{{- end }}