{{- $quay := .Values.quay }}
---
  {{- $secretName := include "quay.superUserSecretName" . -}}
  {{- $secretObj := (lookup "v1" "Secret" $quay.namespace $secretName) | default dict -}}
  {{- $secretData := (get $secretObj "data") | default dict -}}
  {{- $username := (get $secretData "username") | default ($quay.config.superUser.name | b64enc) -}}
  {{- $password := (get $secretData "password") | default (randAlphaNum 16 | b64enc) -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: quay
  namespace: {{ $quay.namespace }}
  name: {{ $secretName }}
type: Opaque
data:
  username: {{ $username }}
  password: {{ $password }}
