---
quay:
  # Toggles the Quay image registry service.
  enabled: false
  # Target namespace for the Quay registry.
  namespace: __OVERWRITE_ME__
  # Quay registry name.
  name: rhtap-quay
  # Quay's registry ingress domain.
  ingressDomain: __OVERWRITE_ME__
  # Quay's organization configuration.
  organization:
    # Organization's name.
    name: rhtap
    # Organization's email.
    email: __OVERWRITE_ME__
  repository:
    # Repository's name
    name: default
  # Quay admin "docker-registry" secret namespace and name.
  secret:
    namespace: __OVERWRITE_ME__
    name: __OVERWRITE_ME__
  # Quay robot name for organization
  robot:
    name: rhtap_rw
  robotReadonly:
  # Quay robot name with read-only pemission
    name: rhtap_ro
  # Quay configuration bundle.
  config:
    # Quay's instance adminstration user.
    superUser:
      # Admin (super-user) username.
      name: admin
      # Admin's email.
      email: __OVERWRITE_ME__
  # Enable managed HPA for Quay components, when enabled the
  # `components.*.replicas` won't be used.
  horizontalPodAutoScaler: false
  # Override parts of the Quay managed components configuration.
  componentOverrides:
    # Quay registry application.
    quay:
      replicas: 2
      resources: &quayResources
        limits:
          memory: 4480Mi
        requests:
          memory: 256Mi
    # Quay registry application database.
    postgres:
      resources: &postgresResources
        limits:
          memory: 768Mi
        requests:
          memory: 128Mi
    # Clair vulnerability scanner.
    clair:
      replicas: 1 
      resources: *quayResources
    # Clair vulnerability scanner local database.
    clairpostgres:
      resources: *postgresResources

