---
apiVersion: v2
name: tssc-minio-operator
description: Helm Chart to manage the MinIO Operator for RHTAP
type: application
version: 1.5.0
appVersion: "5.0.17"
# !!! When updating the chart version, make sure to update the image references in:
# !!!     - installer/charts/tssc-infrastructure/templates/minio/tenants.yaml
# !!!     - installer/charts/tssc-minio-operator/values.yaml
dependencies:
  - name: operator
    version: 5.0.17
    condition: minIOOperator.enabled
