---
apiVersion: appstudio.redhat.com/v1beta2
kind: IntegrationTestScenario
metadata:
  name: pr-e2e-tests
  labels:
    test.appstudio.openshift.io/optional: 'false'
spec:
  application: rhtap-cli
  contexts:
    - description: PR testing
      name: pull_request
  params:
    - name: konflux-test-infra-secret
      value: konflux-test-infra
    - name: cloud-credential-key
      value: qe-cloud-credentials-us-east-1
  resolverRef:
    params:
      - name: url
        value: 'https://github.com/redhat-appstudio/rhtap-cli'
      - name: revision
        value: main
      - name: pathInRepo
        value: integration-tests/pipelines/e2e-main-pipeline.yaml
    resolver: git
