apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manage-plr
subjects:
- kind: ServiceAccount
  name: appstudio-pipeline
  apiGroup: ""
roleRef:
  kind: Role
  name: plr-manager
  apiGroup: rbac.authorization.k8s.io
