apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: plr-manager
rules:
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  verbs:
  - get
  - watch
  - list
  - update
  - patch
  - delete
  - create
- apiGroups:
  - tekton.dev
  resources:
  - taskruns
  verbs:
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - watch
  - list
