{{- $saName := "rhdh-kubernetes-plugin" }}
{{- $secretName := "rhtap-k8s-integration" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ $saName }}
type: kubernetes.io/service-account-token

---
{{- $sa := lookup "v1" "serviceAccount" .Release.Name $saName -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $saName }}
  namespace: {{ .Release.Namespace }}
{{- $secrets := (get $sa "secrets" | default list) }}
secrets:
  {{- /* Patch ServiceAccount secrets */}}
  {{- $secretExists := false }}
  {{- range $secrets }}
  - name: {{ .name }}
    {{- if eq .name $secretName }}
      {{- $secretExists = true }}
    {{- end }}
  {{- end }}
  {{- if not $secretExists }}
  - name: {{ $secretName }}
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $saName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: {{ $saName }}
    namespace: {{ .Release.Namespace }}
