apiVersion: batch/v1
kind: Job
metadata:
  name: delete-tekton-config-if-exists
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 8
  template:
    spec:
      serviceAccountName: delete-tekton-config-sa
      restartPolicy: OnFailure
      containers:
        - name: delete-tekton-config
          image: quay.io/openshift/origin-cli:latest
          resources:
            limits:
              memory: 128Mi
          command:
            - /bin/bash
            - -c
            - |
              if [[ "{{ .Values.subscriptions.openshiftPipelines.managed }}" == "true" ]]; then
                  echo "Deleting TektonConfig resource if it exists to allow helm to own the resource"
                  oc delete tektonconfig config --ignore-not-found
              else
                  echo "Skipping TektonConfig resource delete as pipeline subscription is not managed"
              fi
              if [[ $? -ne 0 ]]; then
                  echo "Sleeping for 5 seconds before letting job restart pod"
                  sleep 5
                  exit 1
              fi
