apiVersion: v1
kind: ServiceAccount
metadata:
  name: delete-tekton-config-sa
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.postDeployDeleteLabels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: delete-tekton-config-role
  labels: {{- include "common.postDeployDeleteLabels" . | nindent 4 }}
rules:
  - apiGroups: ["operator.tekton.dev"]
    resources: ["tektonconfigs"]
    verbs: ["get", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: delete-tekton-config-rolebinding
  labels: {{- include "common.postDeployDeleteLabels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: delete-tekton-config-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: delete-tekton-config-role
  apiGroup: rbac.authorization.k8s.io
