{{- if .Values.backingServices.quay.enabled -}}
  {{- $quay := .Values.backingServices.quay }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: quay
  namespace: {{ $quay.namespace }}
  name: {{ include "backingServices.quay.configSecretName" . }}  
type: Opaque
stringData:
  config.yaml: |
    {{ include "backingServices.quay.s3storage.configYAML" . | nindent 4 }}
{{- end }}
