---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    rhdh.redhat.com/backstage-name: {{ .Values.developerHub.instanceName }}
  labels:
    rhdh.redhat.com/ext-config-sync: 'true'
  name: tssc-developer-hub-app-config
data:
  app-config.tssc.yaml: |
{{- include "tssc-dh.app-conf" . | indent 4 }}
