---
apiVersion: rhdh.redhat.com/v1alpha3
kind: Backstage
metadata:
  name: {{ .Values.developerHub.instanceName }}
  namespace: {{ .Release.Namespace }}
spec:
  application:
    appConfig:
      mountPath: /opt/app-root/src
      configMaps:
        - name: tssc-developer-hub-app-config
    dynamicPluginsConfigMapName: tssc-developer-hub-dynamic-plugins
    extraEnvs:
      secrets:
        - name: tssc-developer-hub-env
    route:
      enabled: true
  database:
    enableLocalDb: true
  deployment:
    patch:
      spec:
        template:
          spec:
            volumes:
              - $patch: replace
                name: dynamic-plugins-root
                persistentVolumeClaim:
                  claimName: {{ .Values.developerHub.instanceName }}-dynamic-plugins-root
