kind: ConfigMap
apiVersion: v1
metadata:
  annotations:
    rhdh.redhat.com/backstage-name: {{ .Values.developerHub.instanceName }}
  labels:
    rhdh.redhat.com/ext-config-sync: 'true'
  name: tssc-developer-hub-dynamic-plugins
data:
  dynamic-plugins.yaml: |
{{- include "tssc-dh.plugins-conf" . | indent 4 }}
