kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.developerHub.instanceName }}-dynamic-plugins-root
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
