{{- range $k, $v := include "infrastructure.minIOTenants.enabled" . | fromYaml }}
---
  {{- $rootSecretObj := (lookup "v1" "Secret" $v.namespace $v.rootSecretName) | default dict -}}
  {{- $rootSecretData := (get $rootSecretObj "data") | default dict -}}
  {{- $username := (get $rootSecretData "username") | default ("minio" | b64enc) -}}
  {{- $password := (get $rootSecretData "password") | default (randAlphaNum 16 | b64enc) -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: minio
    v1.min.io/tenant: {{ $k }}
  namespace: {{ $v.namespace }}
  name: {{ $v.rootSecretName }} 
type: Opaque
data:
  username: {{ $username }}
  password: {{ $password }}
stringData:
  config.env: |-
    export MINIO_ROOT_USER="{{ $username | b64dec }}"
    export MINIO_ROOT_PASSWORD="{{ $password | b64dec }}"
{{- end }}
