{{ $argoCD := .Values.appNamespaces.argoCD.name }}
{{- range .Values.appNamespaces.namespace_prefixes }}
  {{- $namespace := . }}
  {{- range tuple "ci" "development" "prod" "stage" }}
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    argocd.argoproj.io/managed-by: {{ $argoCD }}
  name: {{ $namespace }}-{{ . }}
  {{- end }}
{{- end }}