{{- if .Values.backingServices.keycloak.enabled }}
  {{- $keycloakName := include "backingServices.keycloak.name" . -}}
  {{- $keycloak := .Values.backingServices.keycloak -}}
---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  labels:
    app: keycloak
  namespace: {{ $keycloak.namespace }}
  name: {{ $keycloakName }}
spec:
  instances: 1
  additionalOptions:
    - name: enable-recovery
      value: "true"
  {{- if not $keycloak.route.tls.enabled }}
    - name: hostname-strict-https
      value: "false"
  {{- end }}
  transaction:
    xaEnabled: true
  db:
    vendor: postgres
    database: {{ $keycloak.database.name }}
    host: {{ $keycloak.database.host }}
    usernameSecret:
      name: {{ $keycloak.database.secretName }}
      key: user
    passwordSecret:
      name: {{ $keycloak.database.secretName }}
      key: password
  hostname:
    hostname: {{ $keycloak.route.host }}
    strict: false
    strictBackchannel: false
  http:
  {{- if $keycloak.route.tls.enabled }}
    httpEnabled: false
  {{- else }}
    httpEnabled: true
  {{- end }}
    tlsSecret: {{ $keycloak.route.tls.secretName }}
  ingress:
    enabled: false
{{- end }}
