{{- $quay := .Values.quay }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: quay
  namespace: {{ $quay.namespace }}
  name: {{ include "quay.configSecretName" . }}  
type: Opaque
stringData:
  config.yaml: |
    {{ include "quay.s3storage.configYAML" . | nindent 4 }}
